name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Auto-Fix Project and Build
        run: |
          # Gradlew ဖိုင်မရှိရင် အသစ်ပြန်ဆောက်မယ်
          gradle wrapper
          chmod +x gradlew
          
          # Error တက်ရင်တောင် ကျော်ပြီး build မယ်
          ./gradlew assembleDebug --no-daemon --stacktrace || echo "Build Failed but checking APK"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CyberVPN-Final-Result
          path: "**/*.apk"
